# Indiswipe feature extraction (trajectory (4 coord feats: xy + velocities) + nearest_key)
- type: trajectory
  params:
    include_dt: false
    include_velocities: true
    include_accelerations: false

- type: nearest_key
  params:
    use_lookup: true
